dataset:
  name: ODE_Lorenz
  pair_id: [1,2,3,4,5,6,7,8,9]
model:
  name: neural_ode
  train_split: 0.8   # float in (0.7 and 1.0)
                     # proportion of train data to use for training
  seed: 0
  method: normalize
  epochs: 100
  n_trials: 3

hyperparameters:
  hidden_dim:
    lower_bound: 8
    type: randint
    upper_bound: 1024
  lr:
    lower_bound: 1.0e-05
    type: loguniform
    upper_bound: 0.01
  seq_len:
    lower_bound: 5
    type: randint
    upper_bound: 74
  batch_size:
    lower_bound: 5
    type: randint
    upper_bound: 120
